// SPDX-License-Identifier: GPL-3.0-or-later
pragma solidity ^0.8.30;

import {Test} from "forge-std/Test.sol";

/// @notice Pins scripts/allowlist-merkle.ts to SeaDrop's on-chain verification.
///         SeaDrop computes `keccak256(abi.encode(minter, mintParams))` and verifies with
///         OpenZeppelin MerkleProof (sorted pairs). The fixtures below were generated by
///         the TS script for wallets 0xA11CE, 0xB0B, 0xCafE with START_TIME=1700000000,
///         END_TIME=1700604800. If the script's encoding drifts, this test fails.
contract NekoAllowListLeafTest is Test {
    /// @dev Mirror of SeaDrop's MintParams; only needed for leaf encoding in this test.
    struct MintParams {
        uint256 mintPrice;
        uint256 maxTotalMintableByWallet;
        uint256 startTime;
        uint256 endTime;
        uint256 dropStageIndex;
        uint256 maxTokenSupplyForStage;
        uint256 feeBps;
        bool restrictFeeRecipients;
    }

    bytes32 private constant FIXTURE_ROOT =
        0x7378689e5e3b9d28cd26b57766a246f72410496a64f3e92395fb0b2022579cf4;
    address private constant FIXTURE_MINTER = address(0xA11CE);

    function testTsScriptLeafAndProofMatchSeaDropVerification() public pure {
        // The free-stage leaf of the first wallet, exactly as the TS script builds it.
        MintParams memory params = MintParams({
            mintPrice: 0,
            maxTotalMintableByWallet: 3,
            startTime: 1_700_000_000,
            endTime: 1_700_604_800,
            dropStageIndex: 1,
            maxTokenSupplyForStage: 4663,
            feeBps: 1000,
            restrictFeeRecipients: true
        });
        bytes32 leaf = keccak256(abi.encode(FIXTURE_MINTER, params));

        bytes32[] memory proof = new bytes32[](2);
        proof[0] = 0x2df955b96f608afc4f8742d763b0d1d6f36ca9543c6410be4eb156eb5514d958;
        proof[1] = 0xddeb5bc1f2f3e7a12c7b9050abb8a823de204d5a72c8918b13ce7086014568b2;

        // OpenZeppelin MerkleProof.processProof: sorted-pair hashing up to the root.
        bytes32 computed = leaf;
        for (uint256 i; i < proof.length; ++i) {
            computed = computed < proof[i]
                ? keccak256(abi.encodePacked(computed, proof[i]))
                : keccak256(abi.encodePacked(proof[i], computed));
        }

        assertEq(computed, FIXTURE_ROOT, "TS merkle output does not verify like SeaDrop would");
    }
}
